In [149]:
import torch
import torch.nn
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device 


'cuda'

In [42]:
#Check time operation took:
start_time = time.time()
#Operations:
a = torch.ones(2,5)
b=torch.zeros(2,2)

end_time = time.time()
elapsed_time =end_time-start_time
print(f"{elapsed_time:.10f}")


0.0002608299


In [20]:
randint = torch.randint(-100,100, (6,))
randint

tensor([  6, -42, -14,  65, -95,  69])

In [22]:
tensor = torch.tensor([[1,3],[3,6],[7,9]])
tensor

tensor([[1, 3],
        [3, 6],
        [7, 9]])

In [23]:
zeros = torch.zeros(3,3)
zeros


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [32]:
#Creates a tensor containing numbers in a sequence with a fixed step size:Similar as range in python
#torch.arange(5) means:start = 0 (default)end = 5step = 1 (default)
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [26]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [29]:
#10start to 10end in 5 steps
logspace = torch.logspace(start=-10,end=10,steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [30]:
#creates an identity matrix.
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [35]:
#torch.empty_like() creates a new tensor with the same shape and datatype as another tensor, but the values are uninitialized (random garbage values already in memory).
a = torch.empty((2,3), dtype =torch.int64 )
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [45]:
#Lets check if numpy'cpu' is faster or torch'cuda' as in gpu is faster
torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)

start_time = time.time()
# The '@' operator performs Matrix Multiplication (Dot Product)
res_torch = (torch_rand1 @ torch_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"PyTorch Matrix Mult Time: {elapsed_time:.8f}")

# 2. NumPy Setup (Element-wise Multiplication)
# Note: To make it a fair comparison, I'm converting the torch tensors to numpy
np_rand1 = torch_rand1.cpu().numpy()
np_rand2 = torch_rand2.cpu().numpy()

start_time = time.time()
# np.multiply performs Element-wise multiplication (much simpler than @)
res_np = np.multiply(np_rand1, np_rand2)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"NumPy Element-wise Mult Time: {elapsed_time:.8f}")

PyTorch Matrix Mult Time: 0.00026703
NumPy Element-wise Mult Time: 0.07182312


In [99]:
#Index 0: Has a 10% chance of being picked.
#Index 1: Has a 90% chance of being picked.
# 50% chance for Index 0 (Heads), 50% chance for Index 1 (Tails)
probabilities = torch.tensor([0.5,0.5])
"""Distribution	Number of Outcomes	Example
Bernoulli	Exactly 2	A single flip of a fair coin.
Binomial	Exactly 2 (repeated)	Flipping a coin 10 times and counting heads.
Multinomial	2 or more (repeated)	Rolling a 6-sided die 10 times, or picking from your [0.1, 0.9] tensor 9 times."""
samples = torch.multinomial(probabilities,num_samples=9,replacement = True)
print(samples)
# Probability of landing a 1 (Tails) is 0.9
p = 0.9
# "Flip" once: Bernoulis
single_flip = torch.bernoulli(torch.tensor([p]))
print(single_flip)
#A Binomial distribution is what you get when you repeat a Bernoulli trial multiple times and count the successes.
# n = number of trials (9 flips)
# p = probability of success (0.9)
binomial_dist = torch.distributions.Binomial(total_count=9, probs=0.5)

success_count = binomial_dist.sample()
print(success_count) 
# Example output: tensor(8.0)


tensor([0, 0, 0, 1, 0, 0, 1, 1, 1])
tensor([1.])
tensor(3.)


In [89]:
"""torch.cat() is used in PyTorch to concatenate tensors (join tensors together).
Syntax
torch.cat((tensor1, tensor2), dim=0)
dim=0 → join rows  vertical direction ↓
dim=1 → join columnshorizontal direction → """ 


a = torch.tensor([[1, 2],
                  [3, 4]])

b = torch.tensor([[5, 6]])

x = torch.cat((a, b), dim=0)

print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [116]:
#Upper triangular and lower triangular:
out = torch.tril(torch.ones(5,5))
print(out)
out2 = torch.triu(torch.ones(5,5))
print(out2)
#classic "Lego build":common in Transformers and Large Language Models. It is used to create a Look-Ahead Mask
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out


tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [ ]:
"""The Addition: You add this mask to your "Attention Scores" (the raw numbers that decide which words are important).
The Blackout: Adding -inf to any number makes it -inf. The "legal" words stay the same because you added 0."""

In [115]:
#Exp function:
"""The Softmax: When you run Softmax on these numbers, the formula is e^x.
For the zeros: e^0 = 1 (This word gets attention).
For the -infinities: e^{-\infty} = 0 (This word gets zero attention)."""
torch.exp(out)
#Because in attention we want:
"""
allowed positions → keep attention
future positions → probability 0
So the words are in as in 1 and 0 as not to be seen, this is called soft attention masking
""

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [121]:
#Example:
import torch
import torch.nn.functional as F
energy = torch.tensor([
    [10.0, 10.0, 10.0,10.0,10.0],
    [10.0, 10.0, 10.0,10.0,10.0],
    [10.0, 10.0, 10.0,10.0,10.0],
    [10.0, 10.0, 10.0,10.0,10.0],
    [10.0, 10.0, 10.0,10.0,10.0]
])
out = out+energy
print(out)

#For probabilities(percentage of relevance):
"""If Word 1 has a probability of 0.70 (70%), the model thinks that word is the most important "clue" for what it's currently doing.
If Word 2 has a probability of 0.01 (1%), the model thinks that word is basically noise and ignores it.

A Real-World ExampleImagine the AI is processing this sentence:
"The robot picked up the battery because it..."When the
AI reaches the word "it", 
the probabilities (Attention Weights) might look like this:  WordProbabilityMeaningrobot0.85The AI is 85% sure "it" 
refers to the robot.
battery 0.10There is a 10% chance"it" refers to the battery.
picked0.03Very low relevance.
the0.02Almost no relevance.
future words0.00Blocked by your -inf mask."""

probs = F.softmax(out,dim=-1)
print(probs)




tensor([[40., -inf, -inf, -inf, -inf],
        [40., 40., -inf, -inf, -inf],
        [40., 40., 40., -inf, -inf],
        [40., 40., 40., 40., -inf],
        [40., 40., 40., 40., 40.]])
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000]])


In [140]:
input = torch.tensor([[1, 2, 3], 
                    [4, 5, 6]])
out = input.transpose(0,1)
print(out)
 

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [142]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
tensor3 = torch.tensor([1,2,3])
stacked = torch.stack([tensor1,tensor2,tensor3])
stacked

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [146]:
tensor = torch.tensor([1,2,3]).float()
import torch.nn.functional as F
softmax_output = F.softmax(tensor,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [156]:
#Embedding vectors:
import torch.nn as nn
vocab_size = 1000
vect_dim = 100
embeding = nn.Embedding(vocab_size,vect_dim)
tensor = torch.LongTensor([1,2,3])
embedded_output = embeding(tensor)
print(embedded_output.shape)
print(embedded_output)


torch.Size([3, 100])
tensor([[-0.5497,  0.3623, -0.8038,  0.2794,  1.1307,  1.8928,  0.6532,  0.4503,
         -0.9854,  1.0909, -1.1389, -0.6083, -0.5568, -0.1893, -0.9947,  0.3363,
         -1.9954,  0.5615,  0.0950, -0.5725, -1.5844, -0.3720,  0.1351, -0.2893,
          1.6140,  0.4477, -0.3617,  0.2521,  0.8909, -0.2989, -2.6754, -1.3211,
          0.5130,  0.6264,  2.7081,  0.1107, -1.2427, -0.1235, -0.7428,  0.1034,
         -0.3203,  1.1723,  0.3264, -0.6420, -0.7999, -1.6206,  0.7463,  0.4530,
          0.7112,  0.6237, -0.3919,  0.8758,  0.4330, -2.2135, -0.1923, -0.4960,
         -0.4672,  0.1394,  2.9367,  0.1034, -1.2877, -0.0740, -0.5461,  0.5309,
         -1.1929,  3.0348, -0.7088,  0.8482,  0.2677,  0.9624,  0.3870,  1.1245,
         -0.3375, -0.8441,  0.6134, -2.4879, -0.0822,  0.6720,  0.1904,  0.2758,
          2.8790, -0.4965,  1.1324,  0.9249, -0.6261,  0.6351, -0.0402,  0.7407,
          0.7113,  1.6052, -1.3371, -0.3517,  0.5327, -0.7936, -1.1877,  0.0750,
       

In [168]:
tensor1 = torch.randint(1, (3,2)).float()
tensor2 = torch.rand(2,3)
#print(tensor1@tensor2) can only be used for same data typpe
result = torch.matmul(tensor1,tensor2)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
